# Generated by Django 4.2.5 on 2023-09-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idEspecie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especie', verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.IntegerField(max_length=150),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=9),
        ),
    ]
